import type { ParticleDeckVariantConfig } from "../types";

export const classicVariant: ParticleDeckVariantConfig = {
  id: "webgl-particle-deck",
  title: "WebGL Particle Deck",
  description: "Cinematic particle formations with bloom and trails.",
  ui: {
    overlay: "center",
    hintStyle: "minimal",
    progressStyle: "pills",
  },
  render: {
    backgroundOverlay: "none",
    sparkle: 0.35,
    opacity: 0.85,
    bloomScale: 1.0,
    trailsScale: 1.0,
  },
  extras: {
    constellationLines: false,
  },
  slides: [
    {
      id: "scatter",
      title: "Scatter",
      subtitle: "Random becomes a canvas",
      particleColor: "#3B82F6",
      bgColor: "#030712",
      fx: { bloomStrength: 0.6, bloomRadius: 0.4, bloomThreshold: 0.2, trailsDamp: 0.98 },
    },
    {
      id: "curl-flow",
      title: "Curl Flow",
      subtitle: "Fields that feel alive",
      particleColor: "#8B5CF6",
      bgColor: "#0a0118",
      fx: { bloomStrength: 0.9, bloomRadius: 0.55, bloomThreshold: 0.15, trailsDamp: 0.94 },
    },
    {
      id: "orbitals",
      title: "Orbitals",
      subtitle: "Order in motion",
      particleColor: "#22D3EE",
      bgColor: "#021014",
      fx: { bloomStrength: 0.5, bloomRadius: 0.3, bloomThreshold: 0.25, trailsDamp: 1.0 },
    },
    {
      id: "gravity-wells",
      title: "Gravity Wells",
      subtitle: "Attraction and escape",
      particleColor: "#EC4899",
      bgColor: "#120a14",
      fx: { bloomStrength: 1.0, bloomRadius: 0.6, bloomThreshold: 0.12, trailsDamp: 0.95 },
    },
    {
      id: "repulsion-lattice",
      title: "Repulsion",
      subtitle: "Spacing is a force",
      particleColor: "#A7F3D0",
      bgColor: "#02120b",
      fx: { bloomStrength: 0.55, bloomRadius: 0.25, bloomThreshold: 0.28, trailsDamp: 1.0 },
    },
    {
      id: "wave-surface",
      title: "Wave Surface",
      subtitle: "A membrane of points",
      particleColor: "#10B981",
      bgColor: "#031210",
      fx: { bloomStrength: 0.7, bloomRadius: 0.35, bloomThreshold: 0.22, trailsDamp: 1.0 },
    },
    {
      id: "vortex-column",
      title: "Vortex",
      subtitle: "Spiral memory in 3D",
      particleColor: "#34D399",
      bgColor: "#021016",
      fx: { bloomStrength: 1.05, bloomRadius: 0.6, bloomThreshold: 0.12, trailsDamp: 0.94 },
    },
    {
      id: "burst",
      title: "Burst",
      subtitle: "Impulse, then reform",
      particleColor: "#F59E0B",
      bgColor: "#120e03",
      fx: { bloomStrength: 1.2, bloomRadius: 0.65, bloomThreshold: 0.1, trailsDamp: 0.92 },
    },
    {
      id: "flock",
      title: "Flock",
      subtitle: "Rules create behavior",
      particleColor: "#FDE68A",
      bgColor: "#0c0b03",
      fx: { bloomStrength: 0.65, bloomRadius: 0.35, bloomThreshold: 0.22, trailsDamp: 0.97 },
    },
    {
      id: "strange-attractor",
      title: "Attractor",
      subtitle: "Chaos with structure",
      particleColor: "#FB7185",
      bgColor: "#110207",
      fx: { bloomStrength: 1.0, bloomRadius: 0.55, bloomThreshold: 0.14, trailsDamp: 0.93 },
    },
    {
      id: "meaning",
      title: "Meaning",
      subtitle: "Particles become language",
      particleColor: "#FFFFFF",
      bgColor: "#05060a",
      fx: { bloomStrength: 0.85, bloomRadius: 0.5, bloomThreshold: 0.16, trailsDamp: 1.0 },
    },
    {
      id: "glitch-grid",
      title: "Glitch",
      subtitle: "Signal under stress",
      particleColor: "#93C5FD",
      bgColor: "#030712",
      fx: { bloomStrength: 0.55, bloomRadius: 0.25, bloomThreshold: 0.28, trailsDamp: 0.98 },
    },
    {
      id: "singularity",
      title: "Singularity",
      subtitle: "Collapse into a core",
      particleColor: "#A855F7",
      bgColor: "#050013",
      fx: { bloomStrength: 1.25, bloomRadius: 0.7, bloomThreshold: 0.1, trailsDamp: 0.92 },
    },
    {
      id: "webgl",
      title: "WebGL",
      subtitle: "GPU-accelerated beauty",
      particleColor: "#EF4444",
      bgColor: "#120303",
      fx: { bloomStrength: 1.0, bloomRadius: 0.55, bloomThreshold: 0.14, trailsDamp: 0.96 },
    },
  ],
};

